export function parseCode(newCode: string): string {
    switch (newCode) {
        case '00': return 'None';
        case '01': return 'Nintendo Research & Development 1';
        case '08': return 'Capcom';
        case '13': return 'EA (Electronic Arts)';
        case '18': return 'Hudson Soft';
        case '19': return 'B-AI';
        case '20': return 'KSS';
        case '22': return 'Planning Office WADA';
        case '24': return 'PCM Complete';
        case '25': return 'San-X';
        case '28': return 'Kemco';
        case '29': return 'SETA Corporation';
        case '30': return 'Viacom';
        case '31': return 'Nintendo';
        case '32': return 'Bandai';
        case '33': return 'Ocean Software/Acclaim Entertainment';
        case '34': return 'Konami';
        case '35': return 'HectorSoft';
        case '37': return 'Taito';
        case '38': return 'Hudson Soft';
        case '39': return 'Banpresto';
        case '41': return 'Ubi Soft';
        case '42': return 'Atlus';
        case '44': return 'Malibu Interactive';
        case '46': return 'Angel';
        case '47': return 'Bullet-Proof Software';
        case '49': return 'Irem';
        case '50': return 'Absolute';
        case '51': return 'Acclaim Entertainment';
        case '52': return 'Activision';
        case '53': return 'Sammy USA Corporation';
        case '54': return 'Konami';
        case '55': return 'Hi Tech Expressions';
        case '56': return 'LJN';
        case '57': return 'Matchbox';
        case '58': return 'Mattel';
        case '59': return 'Milton Bradley Company';
        case '60': return 'Titus Interactive';
        case '61': return 'Virgin Games Ltd.';
        case '64': return 'Lucasfilm Games';
        case '67': return 'Ocean Software';
        case '69': return 'EA (Electronic Arts)';
        case '70': return 'Infogrames';
        case '71': return 'Interplay Entertainment';
        case '72': return 'Broderbund';
        case '73': return 'Sculptured Software';
        case '75': return 'The Sales Curve Limited';
        case '78': return 'THQ';
        case '79': return 'Accolade';
        case '80': return 'Misawa Entertainment';
        case '83': return 'lozc';
        case '86': return 'Tokuma Shoten';
        case '87': return 'Tsukuda Original';
        case '91': return 'Chunsoft Co.';
        case '92': return 'Video System';
        case '93': return 'Ocean Software/Acclaim Entertainment';
        case '95': return 'Varie';
        case '96': return "Yonezawa/s'pal";
        case '97': return 'Kaneko';
        case '99': return 'Pack-In-Video';
        case '9H': return 'Bottom Up';
        case 'A4': return 'Konami (Yu-Gi-Oh!)';
        case 'BL': return 'MTO';
        case 'DK': return 'Kodansha';
        default: 
            console.warn(`Unknown new licensee code: ${newCode}`);
            return 'Unknown';
    }
}